import fs from 'node:fs';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { processProductionFullChunk } from '../ingest/production-full-coordinator.mjs';

export const REHEARSAL_AUDIENCE='babypark-catalog-rehearsal-v1';
export const REHEARSAL_PORT=18081;
export const REHEARSAL_FAILPOINTS=Object.freeze(['certification.afterCommit','publication.after']);
export const LINK_A_SYSTEMD_PROPERTIES=Object.freeze({User:'babypark-catalog',Group:'babypark-catalog',UMask:'0077',MemoryAccounting:'yes',CPUAccounting:'yes',IOAccounting:'yes',MemoryMax:'536870912',MemoryHigh:'402653184',CPUWeight:'10',IOWeight:'10',Nice:'10',NoNewPrivileges:'yes',PrivateTmp:'yes',ProtectSystem:'strict',ProtectHome:'yes'});
const inside=(candidate,root)=>candidate===root||candidate.startsWith(`${root}${path.sep}`);
export function validateRehearsalConfig(config,env=process.env){
  if(env.BABYPARK_REHEARSAL!=='1')throw new Error('BABYPARK_REHEARSAL must equal 1');const raw=env.BABYPARK_REHEARSAL_ROOT;if(!raw||!path.isAbsolute(raw))throw new Error('BABYPARK_REHEARSAL_ROOT must be absolute');
  const root=fs.realpathSync(raw);if(root!==path.resolve(raw))throw new Error('rehearsal root must not be a symlink alias');const production='/var/lib/babypark-catalog';
  for(const key of ['identityPath','replayPath','storageDir','backupRoot']){if(!config[key])throw new Error(`${key} is required`);const canonical=fs.realpathSync(config[key]);if(!inside(canonical,root)||inside(canonical,production))throw new Error(`${key} must canonicalize inside rehearsal root`);}
  if(config.host!=='127.0.0.1'||config.port!==REHEARSAL_PORT||config.audience!==REHEARSAL_AUDIENCE||!config.ingestEnabled||config.secrets.size===0||![...config.secrets.keys()].every(k=>k.startsWith('rehearsal-')))throw new Error('rehearsal network/audience/KID/ingest guard failed');
  const selected=env.BABYPARK_REHEARSAL_FAILPOINT??null;if(selected&&!REHEARSAL_FAILPOINTS.includes(selected))throw new Error('unknown rehearsal failpoint');return{root,failpoint:selected};
}
export function rehearsalCoordinator(selected,{kill=()=>process.kill(process.pid,'SIGKILL'),coordinator=processProductionFullChunk}={}){return args=>coordinator({...args,failpoint:name=>{if(name===selected)kill();}});}
export function lostFinalResponseFetch(fetchImpl=globalThis.fetch){let dropped=false;return async(url,options={})=>{const response=await fetchImpl(url,options);const final=options.method==='POST'&&options.headers?.['X-BP-Final']==='1';if(final&&!dropped&&response.ok){dropped=true;throw Object.assign(new Error('rehearsal lost final response'),{code:'ECONNRESET'});}return response;};}
export function createRsyncTransfer({host,remotePath='/',sshWrapperPath,spawn=spawnSync}){if(!/^[A-Za-z0-9.-]+$/.test(host??'')||remotePath!=='/'||!path.isAbsolute(sshWrapperPath))throw new Error('invalid rsync transfer input');return buildingPath=>{if(!path.isAbsolute(buildingPath))throw new Error('building path must be absolute');const argv=['-a','--chmod=D700,F600','--protect-args',`--rsh=${sshWrapperPath}`,`${host}:${remotePath}`,`${buildingPath}/`];const result=spawn('rsync',argv,{stdio:'inherit',shell:false});if(result.error)throw result.error;if(result.status!==0)throw new Error(`rsync failed: ${result.status}`);};}
function cliValue(args,name){const prefix=`--${name}=`;const found=args.filter(value=>value.startsWith(prefix));if(found.length!==1||!path.isAbsolute(found[0].slice(prefix.length)))throw new Error(`exact absolute --${name} is required`);return found[0].slice(prefix.length);}
export function buildLinkASystemdRun({unit,workRoot,gatePath,cliArgs,node=process.execPath,gateScript,linkACli}){if(!/^babypark-link-a-[a-f0-9]{8,64}$/.test(unit)||![workRoot,gatePath,gateScript,linkACli].every(path.isAbsolute)||!Array.isArray(cliArgs))throw new Error('invalid systemd runner input');const readOnly=[cliValue(cliArgs,'staged-spool'),cliValue(cliArgs,'catalog-dir'),cliValue(cliArgs,'identity')].join(' '),properties={...LINK_A_SYSTEMD_PROPERTIES,ReadWritePaths:workRoot,ReadOnlyPaths:readOnly};return{properties,argv:['systemd-run','--no-block','--service-type=oneshot','--remain-after-exit',`--unit=${unit}`,...Object.entries(properties).map(([k,v])=>`--property=${k}=${v}`),node,gateScript,gatePath,node,linkACli,...cliArgs]};}
export function parseSystemdShow(text){return Object.fromEntries(String(text).trim().split('\n').filter(Boolean).map(line=>{const at=line.indexOf('=');return[line.slice(0,at),line.slice(at+1)];}));}
export function validateEffectiveProperties(actual,expected){for(const[key,value]of Object.entries(expected))if(String(actual[key])!==String(value))throw new Error(`systemd property mismatch: ${key}`);return true;}
export async function probeCatalogReadability({origin,client,fetchImpl=globalThis.fetch}){if(!/^http:\/\/127\.0\.0\.1:\d+$/.test(origin??'')||typeof client?.state!=='function')throw new Error('invalid rehearsal Catalog probe input');const health=await fetchImpl(`${origin}/health`,{method:'GET',redirect:'manual'});if(!health.ok)throw new Error(`rehearsal Catalog health probe failed: ${health.status}`);const state=await client.state();if(state.status!==200||!state.body||typeof state.body!=='object')throw new Error('rehearsal Catalog state probe failed');return{health_readable:true,state_readable:true};}
export function resourceEvidence(show,linkAReport,guards){const start=BigInt(show.ExecMainStartTimestampMonotonic),end=BigInt(show.ExecMainExitTimestampMonotonic),wallMs=Number((end-start)/1000n),memory=Number(show.MemoryPeak),guardKeys=['staged_spool_unchanged','catalog_unchanged','identity_unchanged','current_unchanged','health_readable','state_readable'];if(!guards||guardKeys.some(key=>typeof guards[key]!=='boolean'))throw new Error('complete resource evidence guards are required');const pass=show.Result==='success'&&show.ExecMainStatus==='0'&&linkAReport.status==='PASS'&&linkAReport.mismatch_count===0&&memory<384*1024*1024&&wallMs<=900000&&guardKeys.every(key=>guards[key]);return{schema:'bp.catalog.link-a-resource-evidence/1',version:1,status:pass?'PASS':'FAIL',result:show.Result,exec_main_status:Number(show.ExecMainStatus),memory_peak:memory,cpu_usage_nsec:Number(show.CPUUsageNSec),io_read_bytes:Number(show.IOReadBytes),io_write_bytes:Number(show.IOWriteBytes),wall_ms:wallMs,guards:Object.fromEntries(guardKeys.map(key=>[key,guards[key]]))};}
