location = /api/catalog/ingest/v1/full {
    allow 77.83.102.249;
    deny all;

    proxy_pass http://127.0.0.1:8081;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_request_buffering on;

    client_max_body_size 1m;

    proxy_connect_timeout 3s;
    proxy_send_timeout 60s;
    proxy_read_timeout 300s;

    access_log /var/log/nginx/babypark_catalog_ingest_access.log;
    error_log /var/log/nginx/babypark_catalog_ingest_error.log;
}

location = /api/catalog/ingest/v1/state {
    allow 77.83.102.249;
    deny all;

    proxy_pass http://127.0.0.1:8081;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    proxy_request_buffering on;

    client_max_body_size 1m;

    proxy_connect_timeout 3s;
    proxy_send_timeout 60s;
    proxy_read_timeout 300s;

    access_log /var/log/nginx/babypark_catalog_ingest_access.log;
    error_log /var/log/nginx/babypark_catalog_ingest_error.log;
}
