import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {spawnSync}from'node:child_process';
import {stageFrozenSpoolFromTransfer}from'../../src/catalog/link-a/staging.mjs';import{createD2bFixture}from'../helpers/drupal-d2b-sender-fixture.mjs';import{LINK_A_SYSTEMD_PROPERTIES,REHEARSAL_AUDIENCE,buildLinkASystemdRun,createRsyncTransfer,lostFinalResponseFetch,parseSystemdShow,rehearsalCoordinator,resourceEvidence,validateEffectiveProperties,validateRehearsalConfig}from'../../src/catalog/rehearsal/operations.mjs';
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function copy(source,target){for(const name of fs.readdirSync(source)){fs.copyFileSync(path.join(source,name),path.join(target,name));fs.chmodSync(path.join(target,name),0o600);}}
test('Link A CLI malformed input is one bounded JSON and exit 2',()=>{const r=spawnSync(process.execPath,['scripts/catalog-link-a.mjs','badarg'],{cwd:process.cwd(),encoding:'utf8'});assert.equal(r.status,2);assert.equal(r.stderr,'');assert.equal(r.stdout.trim().split('\n').length,1);assert.equal(JSON.parse(r.stdout).status,'ERROR');});
test('transfer staging promotes exact artifact once and retains failures',async t=>{const f=createD2bFixture(),root=path.join(f.root,'staging');fs.mkdirSync(root,{mode:0o700});t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const expected=hash(fs.readFileSync(path.join(f.spool,'manifest.json'))),result=await stageFrozenSpoolFromTransfer({stagingRoot:root,expectedManifestSha256:expected,transfer:building=>copy(f.spool,building)});assert.match(result.path,/\.staged$/);await assert.rejects(stageFrozenSpoolFromTransfer({stagingRoot:root,expectedManifestSha256:expected,transfer(){}}),/already exists/);});
test('transfer staging rejects wrong trusted hash and keeps building',async t=>{const f=createD2bFixture(),root=path.join(f.root,'staging');fs.mkdirSync(root,{mode:0o700});t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const wrong='0'.repeat(64);await assert.rejects(stageFrozenSpoolFromTransfer({stagingRoot:root,expectedManifestSha256:wrong,transfer:b=>copy(f.spool,b)}));assert.ok(fs.existsSync(path.join(root,`${wrong}.building`)));assert.equal(fs.existsSync(path.join(root,`${wrong}.staged`)),false);});
test('transfer staging rejects symlink and unexpected entries',async t=>{for(const kind of ['symlink','unexpected']){const f=createD2bFixture(),root=path.join(f.root,'staging');fs.mkdirSync(root,{mode:0o700});t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const expected=hash(fs.readFileSync(path.join(f.spool,'manifest.json')));await assert.rejects(stageFrozenSpoolFromTransfer({stagingRoot:root,expectedManifestSha256:expected,transfer:b=>{copy(f.spool,b);if(kind==='symlink'){fs.unlinkSync(path.join(b,'preflight.json'));fs.symlinkSync('/dev/null',path.join(b,'preflight.json'));}else fs.writeFileSync(path.join(b,'extra'),'x',{mode:0o600});}}));}});
test('transfer staging rejects incomplete transfer, path alias, and pre-existing building',async t=>{const f=createD2bFixture(),root=path.join(f.root,'staging');fs.mkdirSync(root,{mode:0o700});t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const expected=hash(fs.readFileSync(path.join(f.spool,'manifest.json')));await assert.rejects(stageFrozenSpoolFromTransfer({stagingRoot:root,expectedManifestSha256:expected,transfer(){}}));const other='1'.repeat(64);fs.mkdirSync(path.join(root,`${other}.building`),{mode:0o700});await assert.rejects(stageFrozenSpoolFromTransfer({stagingRoot:root,expectedManifestSha256:other,transfer(){}}),/already exists/);const alias=path.join(f.root,'alias');fs.symlinkSync(root,alias);await assert.rejects(stageFrozenSpoolFromTransfer({stagingRoot:alias,expectedManifestSha256:'2'.repeat(64),transfer(){}}),/Symlinked/);});
test('rehearsal guard rejects missing flag, production aliases, audience KID and failpoints',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'rehearsal-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));for(const name of ['identity','replay','catalog','backup'])fs.mkdirSync(path.join(root,name));const config={identityPath:path.join(root,'identity'),replayPath:path.join(root,'replay'),storageDir:path.join(root,'catalog'),backupRoot:path.join(root,'backup'),host:'127.0.0.1',port:18081,audience:REHEARSAL_AUDIENCE,secrets:new Map([['rehearsal-key','x']]),ingestEnabled:true};assert.throws(()=>validateRehearsalConfig(config,{}));assert.throws(()=>validateRehearsalConfig({...config,audience:'production'},{BABYPARK_REHEARSAL:'1',BABYPARK_REHEARSAL_ROOT:root}));assert.throws(()=>validateRehearsalConfig(config,{BABYPARK_REHEARSAL:'1',BABYPARK_REHEARSAL_ROOT:root,BABYPARK_REHEARSAL_FAILPOINT:'other'}));assert.equal(validateRehearsalConfig(config,{BABYPARK_REHEARSAL:'1',BABYPARK_REHEARSAL_ROOT:root}).root,root);});
test('exact rehearsal failpoints fire only at named hook',()=>{for(const selected of ['certification.afterCommit','publication.after']){const seen=[];const wrapped=rehearsalCoordinator(selected,{kill:()=>seen.push('kill'),coordinator:args=>{for(const name of ['other',selected,'later'])args.failpoint(name);return'ok';}});assert.equal(wrapped({}),'ok');assert.deepEqual(seen,['kill']);}});
test('lost-final wrapper drops first successful exact final response only',async()=>{const calls=[],fetch=lostFinalResponseFetch(async(_u,o)=>{calls.push(o);return{ok:true,status:200}}),headers={'X-BP-Final':'1'};await assert.rejects(fetch('x',{method:'POST',headers}));assert.equal((await fetch('x',{method:'POST',headers})).status,200);assert.equal((await fetch('x',{method:'POST',headers:{'X-BP-Final':'0'}})).status,200);assert.equal(calls[0].body,calls[1].body);});
test('systemd command properties and metric state are exact',()=>{const built=buildLinkASystemdRun({unit:'babypark-link-a-deadbeef',workRoot:'/work',gatePath:'/work/gate',gateScript:'/release/gate.mjs',cliArgs:['--x=y'],node:'/node'});assert.equal(built.argv[1],'--no-block');assert.ok(built.argv.includes('--service-type=oneshot'));assert.ok(built.argv.includes('--remain-after-exit'));validateEffectiveProperties({...LINK_A_SYSTEMD_PROPERTIES,ReadWritePaths:'/work'},built.properties);assert.deepEqual(parseSystemdShow('Result=success\nExecMainStatus=0\n'),{Result:'success',ExecMainStatus:'0'});assert.equal(resourceEvidence({Result:'success',ExecMainStatus:'0',MemoryPeak:'1',CPUUsageNSec:'2',IOReadBytes:'3',IOWriteBytes:'4',ExecMainStartTimestampMonotonic:'1000',ExecMainExitTimestampMonotonic:'2000'},{status:'PASS',mismatch_count:0}).status,'PASS');});
test('rsync adapter invokes argv without a shell',()=>{let call;const transfer=createRsyncTransfer({host:'drupal.example',identityFile:'/keys/one',spawn:(command,argv,options)=>(call={command,argv,options},{status:0})});transfer('/stage/building');assert.equal(call.command,'rsync');assert.equal(call.options.shell,false);assert.equal(call.argv.at(-1),'/stage/building/');});
test('production index is unaware of rehearsal environment',()=>{assert.equal(fs.readFileSync('src/catalog/http/index.mjs','utf8').includes('BABYPARK_REHEARSAL'),false);});
