import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { CatalogGenerationBuilder, CatalogPublisher, CatalogReader } from '../../src/catalog/sqlite/generation.mjs';
import { ReplayStore } from '../../src/catalog/ingest/replay-store.mjs';
import { canonicalControlJson, computeRunDigestV2 } from '../../src/catalog/ingest/run-protocol.mjs';
import { resolveFinalAckAgainstCurrent, finishPendingAgainstCurrent, renderAcceptedRunAck } from '../../src/catalog/ingest/current-evidence.mjs';

const canonicalJson=canonicalControlJson;
const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function header(runId='run_1',layer='content',base='g2'){const mode=layer==='full'?'full':'incremental'; const layers=layer==='full'?['taxonomy','content','commercial','stock'].map(layer=>({base_watermark:null,layer,mode:'replace',output_watermark:null,t_high:null,t_low:null})):[{base_watermark:'10',layer,mode:'delta',output_watermark:'12',t_high:'12',t_low:'9'}];return Buffer.from(canonicalJson({header:{base_generation_id:base,layers,run_id:runId,run_kind:mode,schema:'bp.catalog.run-header/1',source_epoch:'epoch-1'}}));}
function protocol(runId='run_1',layer='content',base='g2'){const h=header(runId,layer,base),hh=hash(h),digest=computeRunDigestV2({headerHash:hh,chunkHashes:[],finalSeq:1,count:0}); const body=Buffer.from(canonicalJson({trailer:{count:0,final_seq:1,run_digest:digest,run_header_sha256:hh,schema:'bp.catalog.trailer/2'}})); return {h,digest,body,hkey:{kid:'k1',runId,layer,seq:0,bodySha256:hh,final:false,contentEncoding:'identity'},key:{kid:'k1',runId,layer,seq:1,bodySha256:hash(body),final:true,contentEncoding:'identity'}};}
function setup(t,{layer='content',status='ACCEPTED',savedDigest,finalSeq=1}={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bp-evidence-v2-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true})); const p=protocol('run_1',layer); for(const id of ['g1','g2']){const b=CatalogGenerationBuilder.create({storageDir:dir,generationId:id,sourceEpoch:'epoch-1',identityRevision:0});if(layer!=='full')b.db.prepare("UPDATE sync_state SET accepted_watermark='10' WHERE layer='content'").run();if(id==='g2')b.db.prepare('INSERT INTO ingest_runs(run_id,layer,run_kind,run_digest,final_seq,status,source_watermark,started_at,terminal_at) VALUES(?,?,?,?,?,?,?,?,?)').run('run_1',layer,layer==='full'?'full':'incremental',savedDigest??p.digest,finalSeq,status,layer==='full'?null:'12','now','now');b.seal();} const publisher=new CatalogPublisher(dir);publisher.publish('g1');publisher.publish('g2');const reader=new CatalogReader(dir);const file=path.join(dir,'replay.sqlite');let store=ReplayStore.createNew(file,{catalogStorageDir:dir});t.after(()=>{reader.close();try{store.close()}catch{}});return{dir,p,publisher,reader,get store(){return store},reopen(){store.close();store=ReplayStore.openExisting(file,{catalogStorageDir:dir})}};}
function stageAndClaim(f,p=f.p,fullBuildDb){const c=f.store.claim(p.hkey,100,{verifiedBody:p.h}); if(p.hkey.layer==='full'){fullBuildDb.prepare('INSERT INTO run_chunks(run_id,kid,seq,body_sha256,rows) VALUES(?,?,?,?,0)').run(p.hkey.runId,p.hkey.kid,0,p.hkey.bodySha256);f.store.stage(p.hkey,p.h,c.claimToken,{fullBuildDb});}else f.store.stage(p.hkey,p.h,c.claimToken); return f.store.claim(p.key,100,{verifiedBody:p.body,reader:f.reader});}

test('accepted ACK follows evidence in CURRENT through rollback and roll-forward',t=>{const f=setup(t);stageAndClaim(f);f.reopen();const ack=renderAcceptedRunAck({key:f.p.key,generationId:'g2',runDigest:f.p.digest,sourceWatermark:'12'});assert.deepEqual(finishPendingAgainstCurrent({store:f.store,reader:f.reader,key:f.p.key}),{status:'ACKED',ack});f.publisher.rollbackToPrevious();assert.deepEqual(resolveFinalAckAgainstCurrent({store:f.store,reader:f.reader,key:f.p.key}),{status:'RUN_SUPERSEDED'});f.publisher.rollbackToPrevious();assert.deepEqual(resolveFinalAckAgainstCurrent({store:f.store,reader:f.reader,key:f.p.key}),{status:'ACKED',ack});});

test('a conflicting digest from CURRENT cannot become a signed ACK',t=>{const f=setup(t,{savedDigest:'e'.repeat(64)});stageAndClaim(f);assert.deepEqual(finishPendingAgainstCurrent({store:f.store,reader:f.reader,key:f.p.key}),{status:'RUN_ID_CONFLICT'});});

test('full evidence matches full key; wrong incremental layer is rejected',t=>{const f=setup(t,{layer:'full'});const build=CatalogGenerationBuilder.create({storageDir:f.dir,generationId:'g3',sourceEpoch:'epoch-1',identityRevision:0});t.after(()=>{try{build.db.close()}catch{}});stageAndClaim(f,f.p,build.db);assert.equal(finishPendingAgainstCurrent({store:f.store,reader:f.reader,key:f.p.key}).status,'ACKED');const wrong={...f.p.key,kid:'k2',layer:'content'};assert.throws(()=>f.store.claim(wrong,100,{verifiedBody:f.p.body,reader:f.reader}),e=>['INGEST_REPLAY_CONFLICT','INGEST_REPLAY_SEQUENCE_GAP'].includes(e.code));});

test('stored ACK cannot substitute a watermark absent from CURRENT',t=>{const f=setup(t);stageAndClaim(f);const accepted=finishPendingAgainstCurrent({store:f.store,reader:f.reader,key:f.p.key});assert.equal(accepted.status,'ACKED');const forged={...accepted.ack,source_watermark:'999'};f.store.db.prepare('UPDATE receipts SET ack_json=? WHERE kid=? AND run_id=? AND layer=? AND seq=?').run(canonicalJson(forged),f.p.key.kid,f.p.key.runId,f.p.key.layer,f.p.key.seq);assert.throws(()=>resolveFinalAckAgainstCurrent({store:f.store,reader:f.reader,key:f.p.key}),e=>e.code==='INGEST_REPLAY_ACK_CONFLICT');});

test('ACCEPTED row requires a digest and final sequence',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'bp-e2-schema-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const b=CatalogGenerationBuilder.create({storageDir:dir,generationId:'g1',sourceEpoch:'epoch-1',identityRevision:0});t.after(()=>{try{b.db.close()}catch{}});assert.throws(()=>b.db.prepare("INSERT INTO ingest_runs(run_id,layer,run_kind,status,started_at,terminal_at) VALUES('bad','content','incremental','ACCEPTED','now','now')").run(),/CHECK constraint failed/);assert.throws(()=>b.db.prepare("INSERT INTO ingest_runs(run_id,layer,run_kind,run_digest,final_seq,status,started_at,terminal_at) VALUES('no-watermark','content','incremental',?,1,'ACCEPTED','now','now')").run('d'.repeat(64)),/CHECK constraint failed/);});

test('accepted evidence permits staged-body cleanup without losing final ACK',t=>{const f=setup(t);stageAndClaim(f);assert.equal(f.store.verifyClaimedRunDigest(f.p.key,{reader:f.reader}).runDigest,f.p.digest);assert.equal(f.store.finishPendingAgainstCurrent(f.p.key,f.reader).status,'ACKED');assert.deepEqual(f.store.releaseAcceptedRunBodies(f.p.key,f.reader),{status:'RELEASED',releasedCount:1});assert.equal(f.store.db.prepare('SELECT staged_body IS NULL absent FROM receipts WHERE seq=0').get().absent,1);assert.deepEqual(f.store.resolveStagedAck(f.p.hkey),{status:'RUN_SUPERSEDED'});assert.equal(f.store.resolveFinalAckAgainstCurrent(f.p.key,f.reader).status,'ACKED');});
