import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import { frameUtf8 } from '../../src/catalog/ingest/framing.mjs';
import { dimensionId,imageId } from '../../src/catalog/ingest/production-full-mapper.mjs';
import { validateFullRecords } from '../../src/catalog/ingest/full-record-v1.mjs';
import { IdentityStore } from '../../src/catalog/identity/store.mjs';
import { identityConfigStateSha256,productionDependencyFingerprint } from '../../src/catalog/ingest/dependency-fingerprint.mjs';

test('E6a framing and derived IDs are deterministic and unambiguous',()=>{assert.equal(frameUtf8('é').toString('hex'),'00000002c3a9');assert.equal(dimensionId('brand','a','bc'),dimensionId('brand','a','bc'));assert.notEqual(dimensionId('brand','ab','c'),dimensionId('brand','a','bc'));assert.match(imageId('p','x','i'),/^img_[a-f0-9]{32}$/);});
test('E6a validator normalizes language and rejects mixed phase before mutation',()=>{const rows=[{schema:'bp.catalog.full-record/1',type:'brand',phase:0,provider:'p',native_brand_id:'b',name:'B'}];assert.equal(validateFullRecords(rows),rows);assert.throws(()=>validateFullRecords([...rows,{schema:'bp.catalog.full-record/1',type:'product',phase:1,provider:'p',native_product_id:'x',kind:'SIMPLE',localized:{uk:{title:'X'}},variants:[],updated_at:new Date().toISOString()}]),e=>e.code==='FULL_RECORD_PHASE_INVALID');});
test('source resolvers are read-only and fingerprint is deterministic',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'e6a-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const file=path.join(dir,'identity.sqlite');const s=IdentityStore.createNew(file,{idFactory:{product:()=> 'prod_1',variant:()=> 'var_1'}});const p=s.ensureProduct({provider:'p',nativeProductId:'np'});s.ensureVariant({provider:'p',nativeVariantId:'nv',productId:p.product_id,sku:' SKU '});const rev=s.metadata().revision;assert.equal(s.lookupProductBySource({provider:'p',nativeProductId:'np'}).product_id,'prod_1');assert.deepEqual({...s.lookupVariantBySource({provider:'p',nativeVariantId:'nv'})},{variant_id:'var_1',product_id:'prod_1',sku:' SKU ',sku_key:'sku',lifecycle:'active'});assert.equal(s.metadata().revision,rev);assert.equal(identityConfigStateSha256(s),identityConfigStateSha256(s));assert.match(productionDependencyFingerprint(s),/^[a-f0-9]{64}$/);s.close();const ro=IdentityStore.openExisting(file,{readOnly:true});assert.equal(ro.lookupProductBySource({provider:'p',nativeProductId:'np'}).product_id,'prod_1');ro.close();});
