import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { canonicalJson } from '../../src/catalog/ingest/replay-store.mjs';
import { normalizeLinkBSku, parseLinkBPhpVariable, parseLinkBCombination, linkBVariantId, linkBMinorUnits, verifyLinkB, MAX_MISMATCH_BYTES } from '../../src/catalog/link-b/verifier.mjs';

const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const privateWrite = (file, bytes) => fs.writeFileSync(file, bytes, { mode: 0o600 });

function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'link-b-')); const spool = path.join(root, 'positive.ready'); fs.mkdirSync(spool, { mode: 0o700 }); const work = path.join(root, 'work'); fs.mkdirSync(work, { mode: 0o700 });
  const collision = path.join(root, 'collisions.yaml'); privateWrite(collision, 'version: 1\nmappings: []\n');
  const source = { schema: 'bp.drupal.source-acceptance/1', version: 1, provider: 'drupal', source_epoch: 'drupal-prod-v1', snapshot_watermark: '123', stock_sync_unix: 1700000000, producer_inputs: { public_site_url: 'https://shop.example', public_files_url: 'https://files.example', source_currency: { code: 'UAH', precision: 0 } }, selection: { reviewed_cases: [], reviewed_product_group_ids: [], resolved_reviewed_product_group_ids: [], missing_reviewed_product_group_ids: [], reviewed_node_ids: [], deterministic_product_ids: ['10'], high_cardinality_product_ids: [], selected_product_group_ids: ['10'], expanded_selected_node_ids: ['10'], selected_product_ids: ['10'] }, raw: { drupal_variables: [{ name: 'babypark_sync_stock_time_sync', value_base64: Buffer.from('i:1700000000;').toString('base64') }, { name: 'uc_currency_code', value_base64: Buffer.from('s:3:"UAH";').toString('base64') }, { name: 'uc_currency_prec', value_base64: Buffer.from('s:1:"0";').toString('base64') }], active_stores: [{ shop_id: 7 }], nodes: [{ nid: 10, vid: 20, tnid: 0, type: 'product', language: 'ru', title: 'Коляска', status: 1, changed: 1700000010 }], uc_products: [{ nid: 10, vid: 20, model: ' SKU 1 ', sell_price: '12.50000', list_price: null }], bodies: [{ entity_id: 10, summary: 'Коротко', value: 'Опис' }], aliases: [{ pid: 1, source: 'node/10', alias: 'catalog/item', language: 'ru', nid: 10 }], field_status: [{ entity_id: 10, value: 1 }], field_provider: [], taxonomy_membership: [], product_attributes: [], product_options: [], adjustments: [], images: [{ entity_id: 10, delta: 0, fid: 9, uri: 'public://folder/a b.jpg', alt: 'alt', title: null, width: 100, height: 50 }], attributes: [], attribute_options: [], category_terms: [], category_hierarchy: [], brand_terms: [], store_terms: [{ tid: 7, name: 'Store' }], stock: [{ sid: 1, sku: 'sku 1', shop_id: 7, stock: 2, stock_old: 1 }] } };
  const product = { schema: 'bp.catalog.full-record/2', type: 'product', phase: 1, provider: 'drupal', native_product_id: '10', kind: 'SIMPLE', product_type: 'product', localized: { ru: { title: 'Коляска', url: 'https://shop.example/catalog/item', short_description: 'Коротко', description: 'Опис' } }, categories: [], attributes: [], variants: [{ native_variant_id: '10|base', sku: ' SKU 1 ', is_default: true, updated_at: '2023-11-14T22:13:30.000Z', attributes: [], options: {}, commercial_availability: 'IN_STOCK', offer: { current_minor: 1300, regular_minor: null, currency: 'UAH', on_sale: false, tax_included: null }, stock: [{ store_native_id: '7', quantity: 2, source_updated_at: '2023-11-14T22:13:20.000Z' }] }], images: [{ native_image_id: 'fid:9:delta:0', url: 'https://files.example/folder/a%20b.jpg', position: 0, metadata: { fid: 9, uri: 'public://folder/a b.jpg', alt: 'alt', title: null, width: 100, height: 50 } }], updated_at: '2023-11-14T22:13:30.000Z' };
  const phase0Bytes = Buffer.from(canonicalJson({ rows: [{ schema: 'bp.catalog.full-record/2', type: 'store', phase: 0, provider: 'drupal', native_store_id: '7', name: 'Store', active: true }] })); privateWrite(path.join(spool, 'phase0-000001.json'), phase0Bytes);
  const sourceBytes = Buffer.from(`${JSON.stringify(source, null, 2)}\n`); privateWrite(path.join(spool, 'source-acceptance.json'), sourceBytes); const anomaly = { schema: 'bp.catalog.anomaly-report/1', version: 1, anomalies: [] }; const anomalyBytes = Buffer.from(`${JSON.stringify(anomaly, null, 2)}\n`); privateWrite(path.join(spool, 'anomaly-report.json'), anomalyBytes); privateWrite(path.join(spool, 'preflight.json'), '{}\n'); privateWrite(path.join(spool, 'collision-report.json'), '{}\n'); const chunkBytes = Buffer.from(canonicalJson({ rows: [product] })); privateWrite(path.join(spool, 'phase1-000001.json'), chunkBytes);
  const manifest = { schema: 'bp.drupal-exporter.spool/3', version: 3, provider: 'drupal', source_epoch: 'drupal-prod-v1', snapshot_watermark: '123', producer_commit: 'a'.repeat(40), producer_release_provenance_sha256: 'b'.repeat(64), source_acceptance_sha256: sha(sourceBytes), collision_config_sha256: sha(fs.readFileSync(collision)), anomaly_publication_policy_sha256: 'c'.repeat(64), anomaly_report_sha256: sha(anomalyBytes), blocker_count: 0, phase_row_counts: { phase0: 1, phase1: 1 }, chunk_count: 2, chunks: [{ filename: 'phase0-000001.json', phase: 0, rows: 1, bytes: phase0Bytes.length, sha256: sha(phase0Bytes) }, { filename: 'phase1-000001.json', phase: 1, rows: 1, bytes: chunkBytes.length, sha256: sha(chunkBytes) }], total_canonical_rows: 2 }; privateWrite(path.join(spool, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  const rewriteProduct = mutate => { const next = structuredClone(product); mutate(next); const bytes = Buffer.from(canonicalJson({ rows: [next] })); privateWrite(path.join(spool, 'phase1-000001.json'), bytes); manifest.chunks[1] = { ...manifest.chunks[1], bytes: bytes.length, sha256: sha(bytes) }; privateWrite(path.join(spool, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`); };
  return { root, spool, work, collision, rewriteProduct };
}

test('Link B positive retained-source fixture independently matches exact spool projection', t => { const f = fixture(); t.after(() => fs.rmSync(f.root, { recursive: true, force: true })); const report = verifyLinkB({ spoolPath: f.spool, collisionConfigPath: f.collision, workRoot: f.work }); assert.equal(report.status, 'PASS', JSON.stringify(report.mismatches)); assert.equal(report.mismatch_count, 0); assert.equal(report.checked_projection_counts.expected_products, 1); });
test('Link B catches a semantically corrupted but rehashed canonical title', t => { const f = fixture(); t.after(() => fs.rmSync(f.root, { recursive: true, force: true })); f.rewriteProduct(row => { row.localized.ru.title = 'wrong'; }); const report = verifyLinkB({ spoolPath: f.spool, collisionConfigPath: f.collision, workRoot: f.work }); assert.equal(report.status, 'FAIL'); assert.equal(report.mismatches[0].code, 'LINK_B_PROJECTION_MISMATCH'); assert.ok(Buffer.byteLength(JSON.stringify(report.mismatches)) <= MAX_MISMATCH_BYTES); });
test('Link B rejects collision authority bytes before projection', t => { const f = fixture(); t.after(() => fs.rmSync(f.root, { recursive: true, force: true })); fs.appendFileSync(f.collision, '# changed\n'); assert.throws(() => verifyLinkB({ spoolPath: f.spool, collisionConfigPath: f.collision, workRoot: f.work }), /collision config bytes/); });
test('Link B independent normalization, PHP and decimal golden vectors', () => { assert.deepEqual(normalizeLinkBSku(' Cafe\u0301  X '), { sku: 'Café  X', sku_key: 'café  x' }); assert.throws(() => normalizeLinkBSku('x\0y')); assert.equal(parseLinkBPhpVariable(Buffer.from('s:3:"UAH";'), 'string'), 'UAH'); assert.equal(parseLinkBPhpVariable('i:42;', 'integer'), 42); const pairs = parseLinkBCombination('a:2:{i:9;s:2:"11";i:2;i:7;}'); assert.equal(linkBVariantId('10', pairs), '10|opts:2=7,9=11'); assert.equal(linkBMinorUnits(['12.44499'], 0), 1200); assert.equal(linkBMinorUnits(['12.50000'], 0), 1300); });
test('Link B source has a static forbidden-import boundary', () => { const source = fs.readFileSync(new URL('../../src/catalog/link-b/verifier.mjs', import.meta.url), 'utf8'); for (const forbidden of ['canonical/build-from-source.mjs','canonical/records.mjs','canonical/variant-builder.mjs','canonical/localized.mjs','canonical/sku.mjs','decimal-money.mjs','php-combination.mjs','collision/detector.mjs','collision/config.mjs','source-currency.mjs','php-variable.mjs']) assert.equal(source.includes(forbidden), false, forbidden); });
