import assert from 'node:assert/strict'; import http from 'node:http'; import net from 'node:net'; import test from 'node:test';
import {signCanonicalRequest} from '../../src/catalog/ingest/auth.mjs'; import {createCatalogHttpRuntime} from '../../src/catalog/http/app.mjs';
const secret='test-only-secret-at-least-32-chars-long'; const now=1700000000;
function auth(method,path,body,extra={}){const f={method,path,audience:'aud',kid:'kid1',timestamp:String(now),runId:path.endsWith('/state')?'state':'run1',seq:0,final:'0',contentEncoding:'identity',bodyBytes:body,secret};const s=signCanonicalRequest(f);return {'X-BP-Version':'1','X-BP-Aud':'aud','X-BP-Kid':'kid1','X-BP-Timestamp':String(now),'X-BP-Run':f.runId,'X-BP-Seq':'0','X-BP-Final':'0','X-BP-Content-Encoding':'identity','X-BP-Signature':s.signature,...extra}}
function request(address,{method='GET',path='/',body=Buffer.alloc(0),headers={}}={}){return new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port:address.port,method,path,headers},res=>{const chunks=[];res.on('data',x=>chunks.push(x));res.on('end',()=>resolve({status:res.statusCode,headers:res.headers,body:JSON.parse(Buffer.concat(chunks))}))});req.on('error',reject);req.end(body)})}
function raw(address,text){return new Promise((resolve,reject)=>{const socket=net.connect(address.port,'127.0.0.1',()=>socket.end(text));let data='';socket.on('data',x=>data+=x);socket.on('end',()=>resolve(data));socket.on('error',reject)})}
async function runtime(enabled=false){const reader={withDb(){throw Object.assign(new Error(),{code:'CATALOG_CURRENT_MISSING'})}};const r=createCatalogHttpRuntime({config:{host:'127.0.0.1',port:0,ingestEnabled:enabled,audience:'aud',secrets:new Map([['kid1',secret]]),maxAgeSec:300},reader,coordinator:()=>({status:'STAGED',ack:{staged:true,run_id:'run1',layer:'full',seq:0,body_sha256:'a'.repeat(64)}}),logger:{log(){ }},now:()=>now});await r.listen({host:'127.0.0.1',port:0});return r}
test('real HTTP freezes raw routes, methods, fuse, health and authenticated state',async()=>{const r=await runtime();try{assert.equal((await request(r.server.address(),{path:'/health'})).body.state,'BOOTSTRAP');assert.equal((await request(r.server.address(),{path:'/health/'})).status,404);const wrong=await request(r.server.address(),{method:'POST',path:'/api/catalog/ingest/v1/state'});assert.equal(wrong.status,405);assert.equal(wrong.headers.allow,'GET');const body=Buffer.alloc(0);const state=await request(r.server.address(),{path:'/api/catalog/ingest/v1/state',headers:auth('GET','/api/catalog/ingest/v1/state',body)});assert.equal(state.status,200);assert.equal(state.headers['cache-control'],'no-store');const disabled=await request(r.server.address(),{method:'POST',path:'/api/catalog/ingest/v1/full',body:Buffer.from('{}'),headers:{'Content-Type':'application/json'}});assert.equal(disabled.body.code,'INGEST_DISABLED')}finally{await r.close()}});
test('real HTTP authenticates exact bytes and rejects joined/duplicate signed headers',async()=>{const r=await runtime(true);try{const body=Buffer.from('{}');const h=auth('POST','/api/catalog/ingest/v1/full',body,{'Content-Type':'application/json'});assert.equal((await request(r.server.address(),{method:'POST',path:'/api/catalog/ingest/v1/full',body,headers:h})).body.status,'STAGED');const joined={...h,'X-BP-Kid':'kid1, kid2'};assert.equal((await request(r.server.address(),{method:'POST',path:'/api/catalog/ingest/v1/full',body,headers:joined})).body.code,'AUTH_FAILED');const lines=Object.entries(h).filter(([k])=>k.toLowerCase()!=='x-bp-kid').map(([k,v])=>`${k}: ${v}`).join('\r\n');const response=await raw(r.server.address(),`POST /api/catalog/ingest/v1/full HTTP/1.1\r\nHost: localhost\r\nContent-Length: 2\r\n${lines}\r\nX-BP-Kid: kid1\r\nX-BP-Kid: kid1\r\nConnection: close\r\n\r\n{}`);assert.match(response,/HTTP\/1\.1 401/);assert.match(response,/AUTH_FAILED/)}finally{await r.close()}});
test('media, exact route, one MiB precheck, and Expect are bounded',async()=>{const r=await runtime(true);try{const a=r.server.address();assert.equal((await request(a,{method:'POST',path:'/api/catalog/ingest/v1/full?x=1'})).status,404);assert.equal((await request(a,{method:'POST',path:'/api/catalog/ingest/v1/full',body:Buffer.from('{}'),headers:{'Content-Type':'application/json; charset=utf-8'}})).status,415);assert.equal((await request(a,{method:'POST',path:'/api/catalog/ingest/v1/full',headers:{'Content-Type':'application/json','Content-Length':'1048577'}})).status,413);const response=await raw(a,'POST /api/catalog/ingest/v1/full HTTP/1.1\r\nHost: localhost\r\nExpect: 100-continue\r\nContent-Length: 0\r\n\r\n');assert.match(response,/HTTP\/1\.1 417/)}finally{await r.close()}});
