import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { canonicalJson } from '../../src/catalog/ingest/replay-store.mjs';
import { buildAnomalyReport } from '../../src/catalog/anomaly/report.mjs';
import { observationFromCrossProductCollision } from '../../src/catalog/anomaly/observation.mjs';
import { computeFingerprint } from '../../src/catalog/anomaly/fingerprint.mjs';
import { normalizeLinkBSku, parseLinkBPhpVariable, parseLinkBCombination, linkBVariantId, linkBMinorUnits, verifyLinkB, MAX_MISMATCH_BYTES } from '../../src/catalog/link-b/verifier.mjs';

const sha = bytes => crypto.createHash('sha256').update(bytes).digest('hex');
const privateWrite = (file, bytes) => fs.writeFileSync(file, bytes, { mode: 0o600 });

function fixture() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'link-b-')); const spool = path.join(root, 'positive.ready'); fs.mkdirSync(spool, { mode: 0o700 }); const work = path.join(root, 'work'); fs.mkdirSync(work, { mode: 0o700 });
  const collision = path.join(root, 'collisions.yaml'); privateWrite(collision, 'version: 1\nmappings: []\n');
  const source = { schema: 'bp.drupal.source-acceptance/1', version: 1, provider: 'drupal', source_epoch: 'drupal-prod-v1', snapshot_watermark: '123', stock_sync_unix: 1700000000, producer_inputs: { public_site_url: 'https://shop.example', public_files_url: 'https://files.example', source_currency: { code: 'UAH', precision: 0 } }, selection: { reviewed_cases: [], reviewed_product_group_ids: [], resolved_reviewed_product_group_ids: [], missing_reviewed_product_group_ids: [], reviewed_node_ids: [], deterministic_product_ids: ['10'], high_cardinality_product_ids: [], selected_product_group_ids: ['10'], expanded_selected_node_ids: ['10'], selected_product_ids: ['10'] }, raw: { drupal_variables: [{ name: 'babypark_sync_stock_time_sync', value_base64: Buffer.from('i:1700000000;').toString('base64') }, { name: 'uc_currency_code', value_base64: Buffer.from('s:3:"UAH";').toString('base64') }, { name: 'uc_currency_prec', value_base64: Buffer.from('s:1:"0";').toString('base64') }], active_stores: [{ shop_id: 7 }], nodes: [{ nid: 10, vid: 20, tnid: 0, type: 'product', language: 'ru', title: 'Коляска', status: 1, changed: 1700000010 }], uc_products: [{ nid: 10, vid: 20, model: ' SKU 1 ', sell_price: '12.50000', list_price: null }], bodies: [{ entity_id: 10, summary: 'Коротко', value: 'Опис' }], aliases: [{ pid: 1, source: 'node/10', alias: 'catalog/item', language: 'ru', nid: 10 }], field_status: [{ entity_id: 10, value: 1 }], field_provider: [], taxonomy_membership: [], product_attributes: [], product_options: [], adjustments: [], images: [{ entity_id: 10, delta: 0, fid: 9, uri: 'public://folder/a b.jpg', alt: 'alt', title: null, width: 100, height: 50 }], attributes: [], attribute_options: [], category_terms: [], category_hierarchy: [], brand_terms: [], store_terms: [{ tid: 7, name: 'Store' }], stock: [{ sid: 1, sku: 'sku 1', shop_id: 7, stock: 2, stock_old: 1 }] } };
  const product = { schema: 'bp.catalog.full-record/2', type: 'product', phase: 1, provider: 'drupal', native_product_id: '10', kind: 'SIMPLE', product_type: 'product', localized: { ru: { title: 'Коляска', url: 'https://shop.example/catalog/item', short_description: 'Коротко', description: 'Опис' } }, categories: [], attributes: [], variants: [{ native_variant_id: '10|base', sku: ' SKU 1 ', is_default: true, updated_at: '2023-11-14T22:13:30.000Z', attributes: [], options: {}, commercial_availability: 'IN_STOCK', offer: { current_minor: 1300, regular_minor: null, currency: 'UAH', on_sale: false, tax_included: null }, stock: [{ store_native_id: '7', quantity: 2, source_updated_at: '2023-11-14T22:13:20.000Z' }] }], images: [{ native_image_id: 'fid:9:delta:0', url: 'https://files.example/folder/a%20b.jpg', position: 0, metadata: { fid: 9, uri: 'public://folder/a b.jpg', alt: 'alt', title: null, width: 100, height: 50 } }], updated_at: '2023-11-14T22:13:30.000Z' };
  const phase0Bytes = Buffer.from(canonicalJson({ rows: [{ schema: 'bp.catalog.full-record/2', type: 'store', phase: 0, provider: 'drupal', native_store_id: '7', name: 'Store', active: true }] })); privateWrite(path.join(spool, 'phase0-000001.json'), phase0Bytes);
  const sourceBytes = Buffer.from(`${JSON.stringify(source, null, 2)}\n`); privateWrite(path.join(spool, 'source-acceptance.json'), sourceBytes); const anomaly = { schema: 'bp.catalog.anomaly-report/1', version: 1, provider: 'drupal', source_epoch: 'drupal-prod-v1', snapshot_watermark: '123', detector: { namespace: 'fixture', version: 1, authoritative: true }, collision_config_sha256: sha(fs.readFileSync(collision)), anomaly_publication_policy_sha256: 'c'.repeat(64), anomaly_count: 0, quarantined_product_count: 0, anomalies: [] }; let anomalyBytes = Buffer.from(`${JSON.stringify(anomaly, null, 2)}\n`); privateWrite(path.join(spool, 'anomaly-report.json'), anomalyBytes); privateWrite(path.join(spool, 'preflight.json'), '{}\n'); privateWrite(path.join(spool, 'collision-report.json'), '{}\n'); const chunkBytes = Buffer.from(canonicalJson({ rows: [product] })); privateWrite(path.join(spool, 'phase1-000001.json'), chunkBytes);
  const manifest = { schema: 'bp.drupal-exporter.spool/3', version: 3, provider: 'drupal', source_epoch: 'drupal-prod-v1', snapshot_watermark: '123', producer_commit: 'a'.repeat(40), producer_release_provenance_sha256: 'b'.repeat(64), source_acceptance_sha256: sha(sourceBytes), collision_config_sha256: sha(fs.readFileSync(collision)), anomaly_publication_policy_sha256: 'c'.repeat(64), anomaly_report_sha256: sha(anomalyBytes), blocker_count: 0, phase_row_counts: { phase0: 1, phase1: 1 }, chunk_count: 2, chunks: [{ filename: 'phase0-000001.json', phase: 0, rows: 1, bytes: phase0Bytes.length, sha256: sha(phase0Bytes) }, { filename: 'phase1-000001.json', phase: 1, rows: 1, bytes: chunkBytes.length, sha256: sha(chunkBytes) }], total_canonical_rows: 2 }; privateWrite(path.join(spool, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`);
  const rewriteRows = rows => { const bytes = Buffer.from(canonicalJson({ rows })); privateWrite(path.join(spool, 'phase1-000001.json'), bytes); manifest.chunks[1] = { ...manifest.chunks[1], rows:rows.length, bytes: bytes.length, sha256: sha(bytes) }; manifest.phase_row_counts.phase1=rows.length;manifest.total_canonical_rows=rows.length+1;privateWrite(path.join(spool, 'manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`); };
  const rewriteProduct = mutate => { const next = structuredClone(product); mutate(next); rewriteRows([next]); };
  const rewriteSource=mutate=>{mutate(source);const bytes=Buffer.from(`${JSON.stringify(source,null,2)}\n`);privateWrite(path.join(spool,'source-acceptance.json'),bytes);manifest.source_acceptance_sha256=sha(bytes);privateWrite(path.join(spool,'manifest.json'),`${JSON.stringify(manifest,null,2)}\n`);};
  const rewriteCollision=text=>{privateWrite(collision,text);manifest.collision_config_sha256=sha(Buffer.from(text));anomaly.collision_config_sha256=manifest.collision_config_sha256;anomalyBytes=Buffer.from(`${JSON.stringify(anomaly,null,2)}\n`);privateWrite(path.join(spool,'anomaly-report.json'),anomalyBytes);manifest.anomaly_report_sha256=sha(anomalyBytes);privateWrite(path.join(spool,'manifest.json'),`${JSON.stringify(manifest,null,2)}\n`);};
  const rewriteAnomaly=next=>{Object.assign(anomaly,next);anomalyBytes=Buffer.from(`${JSON.stringify(anomaly,null,2)}\n`);privateWrite(path.join(spool,'anomaly-report.json'),anomalyBytes);manifest.anomaly_report_sha256=sha(anomalyBytes);privateWrite(path.join(spool,'manifest.json'),`${JSON.stringify(manifest,null,2)}\n`);};
  const removeProducts=()=>{fs.unlinkSync(path.join(spool,'phase1-000001.json'));manifest.chunks=manifest.chunks.slice(0,1);manifest.chunk_count=1;manifest.phase_row_counts.phase1=0;manifest.total_canonical_rows=1;privateWrite(path.join(spool,'manifest.json'),`${JSON.stringify(manifest,null,2)}\n`);};
  return { root, spool, work, collision, rewriteProduct,rewriteRows,rewriteSource,rewriteCollision,rewriteAnomaly,removeProducts,source,product,manifest };
}

test('Link B positive retained-source fixture independently matches exact spool projection', t => { const f = fixture(); t.after(() => fs.rmSync(f.root, { recursive: true, force: true })); const report = verifyLinkB({ spoolPath: f.spool, collisionConfigPath: f.collision, workRoot: f.work }); assert.equal(report.status, 'PASS', JSON.stringify(report.mismatches)); assert.equal(report.mismatch_count, 0); assert.equal(report.checked_projection_counts.expected_products, 1); });
test('Link B catches a semantically corrupted but rehashed canonical title', t => { const f = fixture(); t.after(() => fs.rmSync(f.root, { recursive: true, force: true })); f.rewriteProduct(row => { row.localized.ru.title = 'wrong'; }); const report = verifyLinkB({ spoolPath: f.spool, collisionConfigPath: f.collision, workRoot: f.work }); assert.equal(report.status, 'FAIL'); assert.equal(report.mismatches[0].code, 'LINK_B_PROJECTION_MISMATCH'); assert.ok(Buffer.byteLength(JSON.stringify(report.mismatches)) <= MAX_MISMATCH_BYTES); });
test('Link B rejects collision authority bytes before projection', t => { const f = fixture(); t.after(() => fs.rmSync(f.root, { recursive: true, force: true })); fs.appendFileSync(f.collision, '# changed\n'); assert.throws(() => verifyLinkB({ spoolPath: f.spool, collisionConfigPath: f.collision, workRoot: f.work }), /collision config bytes/); });
test('Link B independent normalization, PHP and decimal golden vectors', () => { assert.deepEqual(normalizeLinkBSku(' Cafe\u0301  X '), { sku: 'Café  X', sku_key: 'café  x' }); assert.throws(() => normalizeLinkBSku('x\0y')); assert.equal(parseLinkBPhpVariable(Buffer.from('s:3:"UAH";'), 'string'), 'UAH'); assert.equal(parseLinkBPhpVariable('i:42;', 'integer'), 42); const pairs = parseLinkBCombination('a:2:{i:9;s:2:"11";i:2;i:7;}'); assert.equal(linkBVariantId('10', pairs), '10|opts:2=7,9=11'); assert.equal(linkBMinorUnits(['12.44499'], 0), 1200); assert.equal(linkBMinorUnits(['12.50000'], 0), 1300); });
test('Link B source has a static forbidden-import boundary', () => { const source = fs.readFileSync(new URL('../../src/catalog/link-b/verifier.mjs', import.meta.url), 'utf8'); for (const forbidden of ['canonical/build-from-source.mjs','canonical/records.mjs','canonical/variant-builder.mjs','canonical/localized.mjs','canonical/sku.mjs','decimal-money.mjs','php-combination.mjs','collision/detector.mjs','collision/config.mjs','source-currency.mjs','php-variable.mjs']) assert.equal(source.includes(forbidden), false, forbidden); });

test('Link B rejects a missing reviewed group leaked into the canonical spool',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));f.rewriteSource(source=>{source.selection.reviewed_product_group_ids=['99'];source.selection.missing_reviewed_product_group_ids=['99'];});const leaked=structuredClone(f.product);leaked.native_product_id='99';leaked.variants[0].native_variant_id='99|base';f.rewriteRows([f.product,leaked]);const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_UNEXPECTED_SELECTED_PRODUCT'&&row.native_product_id==='99'));});
test('Link B rejects duplicate selected product rows across structurally valid chunks',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const bytes=Buffer.from(canonicalJson({rows:[f.product]})),name='phase1-000002.json';privateWrite(path.join(f.spool,name),bytes);f.manifest.chunks.push({filename:name,phase:1,rows:1,bytes:bytes.length,sha256:sha(bytes)});f.manifest.chunk_count=3;f.manifest.phase_row_counts.phase1=2;f.manifest.total_canonical_rows=3;privateWrite(path.join(f.spool,'manifest.json'),`${JSON.stringify(f.manifest,null,2)}\n`);const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_DUPLICATE_SELECTED_PRODUCT'));});
test('Link B rejects product_kit phase-1 leakage',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));f.rewriteSource(source=>{source.raw.nodes[0].type='product_kit';});const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_UNEXPECTED_SELECTED_PRODUCT'));});
test('Link B rejects corrupt evidence envelope cross-links',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));f.rewriteSource(source=>{source.source_epoch='other';});assert.throws(()=>verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work}),/cross-link/);});
test('Link B rejects invalid selected raw state before accepting projection',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));f.rewriteSource(source=>{source.raw.images[0].uri='private://secret.jpg';});const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_SOURCE_STATE_INVALID'));});
test('Link B work root cannot equal, nest in, or alias into frozen spool',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));for(const workRoot of [f.spool,path.join(f.spool,'nested')]){if(!fs.existsSync(workRoot))fs.mkdirSync(workRoot,{mode:0o700});assert.throws(()=>verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot}),/overlaps/);}const alias=path.join(f.root,'alias');fs.symlinkSync(f.spool,alias);assert.throws(()=>verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:alias}),/Symlinked|overlaps/);});
test('Link B CLI invalid input emits exactly one JSON object and exit 2',()=>{const child=spawnSync(process.execPath,['scripts/catalog-link-b.mjs','not-an-option'],{cwd:path.resolve(new URL('../..',import.meta.url).pathname),encoding:'utf8'});assert.equal(child.status,2);assert.equal(child.stderr,'');const lines=child.stdout.trim().split('\n');assert.equal(lines.length,1);assert.equal(JSON.parse(lines[0]).status,'ERROR');});

function addCollisionProduct(f){f.rewriteSource(source=>{source.selection.reviewed_product_group_ids=['10','20'];source.selection.resolved_reviewed_product_group_ids=['10','20'];source.selection.selected_product_group_ids.push('20');source.selection.expanded_selected_node_ids.push('20');source.selection.selected_product_ids.push('20');source.raw.nodes.push({nid:20,vid:21,tnid:0,type:'product',language:'ru',title:'Другий',status:1,changed:1700000010});source.raw.uc_products.push({nid:20,vid:21,model:'sku 1',sell_price:'12.50000',list_price:null});source.raw.field_status.push({entity_id:20,value:1});});const second=structuredClone(f.product);second.native_product_id='20';second.localized.ru={title:'Другий',url:'https://shop.example/node/20'};second.variants[0].native_variant_id='20|base';second.variants[0].sku='sku 1';return second;}
const excludeProductYaml='version: 1\nmappings:\n  - sku_key: "sku 1"\n    action: exclude_product\n    retain_native_product_id: "10"\n    exclude_native_product_id: "20"\n    reviewed_source: "review:test"\n    reason: "fixture"\n';
test('Link B independently proves and applies exclude_product collisions',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));addCollisionProduct(f);f.rewriteCollision(excludeProductYaml);assert.equal(verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work}).status,'PASS');});
test('Link B rejects exclude_product product leakage and stale mapping evidence',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const second=addCollisionProduct(f);f.rewriteCollision(excludeProductYaml);f.rewriteRows([f.product,second]);let report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_UNEXPECTED_SELECTED_PRODUCT'));fs.rmSync(f.work,{recursive:true});fs.mkdirSync(f.work,{mode:0o700});f.rewriteCollision(excludeProductYaml.replace('sku 1','wrong'));report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_SOURCE_STATE_INVALID'));});

function reportCrossCollision(f,mutate=()=>{}){const observation=observationFromCrossProductCollision({provider:'drupal',sourceEpoch:'drupal-prod-v1',collision:{sku_key:'sku 1',entries:[{native_product_id:'10',native_variant_id:'10|base',source_combination:null,sku:' SKU 1 ',is_default:true},{native_product_id:'20',native_variant_id:'20|base',source_combination:null,sku:'sku 1',is_default:true}]}});const report=buildAnomalyReport({provider:'drupal',sourceEpoch:'drupal-prod-v1',snapshotWatermark:'123',detector:{namespace:observation.detectorNamespace,version:observation.detectorVersion},collisionConfigSha256:f.manifest.collision_config_sha256,anomalyPublicationPolicySha256:'c'.repeat(64),observations:[observation]});mutate(report.anomalies[0]);const entry=report.anomalies[0];entry.material_evidence_sha256=sha(Buffer.from(JSON.stringify(entry.material_evidence)));entry.fingerprint=computeFingerprint({anomalyType:entry.anomaly_type,provider:'drupal',sourceEpoch:'drupal-prod-v1',detectorNamespace:report.detector.namespace,detectorVersion:report.detector.version,identifierKind:entry.identifier.kind,identifierKey:entry.identifier.key});f.rewriteAnomaly(report);}
test('Link B rejects an unreported selected residual cross-product collision',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const second=addCollisionProduct(f);f.rewriteRows([f.product,second]);const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_SOURCE_STATE_INVALID'));});
test('Link B accepts an exact reported residual collision only when affected products are absent',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));addCollisionProduct(f);reportCrossCollision(f);f.removeProducts();const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'PASS',JSON.stringify(report.mismatches));});
for(const [name,mutate]of [['wrong anomaly sku_key',entry=>{entry.identifier.key='wrong';}],['wrong collider identity',entry=>{entry.material_evidence.colliders[0].native_variant_id='wrong';}],['wrong collider is_default',entry=>{entry.material_evidence.colliders[0].is_default=false;}],['wrong collider source_combination',entry=>{entry.material_evidence.colliders[0].source_combination='a:0:{}';}]])test(`Link B rejects ${name}`,t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));addCollisionProduct(f);reportCrossCollision(f,mutate);f.removeProducts();const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_SOURCE_STATE_INVALID'));});
test('Link B rejects selected quarantine anomaly without a raw residual collision',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));addCollisionProduct(f);reportCrossCollision(f);f.rewriteSource(source=>{source.raw.uc_products[1].model='UNIQUE';});f.removeProducts();const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_SOURCE_STATE_INVALID'));});
test('Link B rejects collision mapping when both reviewed mapped groups are missing',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));f.rewriteSource(source=>{source.selection.reviewed_product_group_ids=['10','20'];source.selection.missing_reviewed_product_group_ids=['10','20'];source.selection.resolved_reviewed_product_group_ids=[];source.selection.deterministic_product_ids=[];source.selection.selected_product_group_ids=[];source.selection.expanded_selected_node_ids=[];source.selection.selected_product_ids=[];for(const key of ['nodes','uc_products','bodies','aliases','field_status'])source.raw[key]=[];});f.rewriteCollision(excludeProductYaml);f.removeProducts();const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_SOURCE_STATE_INVALID'));});

function configurableCollision(f,{excludedDefault}){f.rewriteSource(source=>{source.selection.reviewed_product_group_ids=['10'];source.selection.resolved_reviewed_product_group_ids=['10'];source.raw.product_attributes=[{nid:10,aid:1,default_option:excludedDefault?12:11}];source.raw.product_options=[{nid:10,oid:11,cost:'0.00000',price:'0.00000',weight:1,ordering:0},{nid:10,oid:12,cost:'0.00000',price:'0.00000',weight:1,ordering:1}];source.raw.attributes=[{aid:1,name:'Color'}];source.raw.attribute_options=[{oid:11,aid:1,name:'Red'},{oid:12,aid:1,name:'Blue'}];source.raw.adjustments=[{nid:10,combination:'a:1:{i:1;s:2:"11";}',model:'DUP'},{nid:10,combination:'a:1:{i:1;s:2:"12";}',model:'dup'}];});const retained=structuredClone(f.product);retained.kind='CONFIGURABLE';retained.variants=[{native_variant_id:'10|opts:1=11',sku:'DUP',is_default:true,updated_at:'2023-11-14T22:13:30.000Z',attributes:[],options:{'1':{attribute_id:'1',attribute_name:'Color',option_id:'11',option_name:'Red'}},commercial_availability:'IN_STOCK',offer:{current_minor:1300,regular_minor:null,currency:'UAH',on_sale:false,tax_included:null},stock:[]}];f.rewriteRows([retained]);f.rewriteCollision('version: 1\nmappings:\n  - sku_key: "dup"\n    action: exclude_variant\n    native_product_id: "10"\n    retain_native_variant_id: "10|opts:1=11"\n    exclude_native_variant_id: "10|opts:1=12"\n    reviewed_source: "review:test"\n    reason: "fixture"\n');return retained;}
test('Link B promotes retained variant only when excluded variant was old default',t=>{for(const excludedDefault of [true,false]){const f=fixture();try{configurableCollision(f,{excludedDefault});const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'PASS',JSON.stringify(report.mismatches));}finally{fs.rmSync(f.root,{recursive:true,force:true});}}});

function synthesizedDefaultCollision(f){f.rewriteSource(source=>{source.selection.reviewed_product_group_ids=['10'];source.selection.resolved_reviewed_product_group_ids=['10'];source.raw.uc_products[0].model='DUP';source.raw.product_attributes=[{nid:10,aid:1,default_option:12}];source.raw.product_options=[{nid:10,oid:11,cost:'0.00000',price:'0.00000',weight:1,ordering:0},{nid:10,oid:12,cost:'0.00000',price:'0.00000',weight:1,ordering:1}];source.raw.attributes=[{aid:1,name:'Color'}];source.raw.attribute_options=[{oid:11,aid:1,name:'Red'},{oid:12,aid:1,name:'Blue'}];source.raw.adjustments=[{nid:10,combination:'a:1:{i:1;s:2:"11";}',model:'dup'}];});const retained=structuredClone(f.product);retained.kind='CONFIGURABLE';retained.variants=[{native_variant_id:'10|opts:1=11',sku:'dup',is_default:true,updated_at:'2023-11-14T22:13:30.000Z',attributes:[],options:{'1':{attribute_id:'1',attribute_name:'Color',option_id:'11',option_name:'Red'}},commercial_availability:'IN_STOCK',offer:{current_minor:1300,regular_minor:null,currency:'UAH',on_sale:false,tax_included:null},stock:[]}];f.rewriteRows([retained]);f.rewriteCollision('version: 1\nmappings:\n  - sku_key: "dup"\n    action: exclude_variant\n    native_product_id: "10"\n    retain_native_variant_id: "10|opts:1=11"\n    exclude_native_variant_id: "10|opts:1=12"\n    reviewed_source: "review:67463"\n    reason: "synthesized default fixture"\n');return retained;}
test('Link B proves synthesized-default exclusion and retained adjustment promotion',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));synthesizedDefaultCollision(f);const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'PASS',JSON.stringify(report.mismatches));});
for(const [name,mutate]of [['wrong SKU',variant=>{variant.sku='WRONG';}],['wrong structural ID',variant=>{variant.native_variant_id='10|opts:1=99';}],['wrong default promotion',variant=>{variant.is_default=false;}]])test(`Link B rejects synthesized-default ${name}`,t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const retained=synthesizedDefaultCollision(f);mutate(retained.variants[0]);f.rewriteRows([retained]);if(name==='wrong default promotion')assert.throws(()=>verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work}),/exactly one default/);else{const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_PROJECTION_MISMATCH'));}});

for(const [name,mutate]of [['canonical category ID collision',source=>{source.raw.category_terms=[{tid:5,vid:1,name:'A',language:'ru',i18n_tsid:0},{tid:6,vid:1,name:'B',language:'uk',i18n_tsid:5}];}],['category hierarchy cycle',source=>{source.raw.category_terms=[{tid:1,vid:1,name:'A',language:'ru',i18n_tsid:0},{tid:2,vid:1,name:'B',language:'ru',i18n_tsid:0}];source.raw.category_hierarchy=[{tid:1,parent:2},{tid:2,parent:1}];}]])test(`Link B rejects ${name}`,t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));f.rewriteSource(mutate);const report=verifyLinkB({spoolPath:f.spool,collisionConfigPath:f.collision,workRoot:f.work});assert.equal(report.status,'FAIL');assert.ok(report.mismatches.some(row=>row.code==='LINK_B_SOURCE_STATE_INVALID'));});
