import test from 'node:test'; import assert from 'node:assert/strict'; import crypto from 'node:crypto'; import fs from 'node:fs'; import os from 'node:os'; import path from 'node:path';
import { validateOrigin } from '../../src/drupal-d2b/config.mjs';
import { verifySpool, readVerifiedChunk } from '../../src/drupal-d2b/spool.mjs';
import { createRunState, readRunState, updateRunState, validateRunState, writeRunState } from '../../src/drupal-d2b/run-state.mjs';
import { acquireSenderLock, breakStaleSenderLock, inspectSenderLock } from '../../src/drupal-d2b/spool-lock.mjs';
import { sendSpool } from '../../src/drupal-d2b/sender.mjs';
import { parseRunHeader, parseTrailerV2 } from '../../src/catalog/ingest/run-protocol.mjs';

const hash=b=>crypto.createHash('sha256').update(b).digest('hex');
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'d2b-'));const release=path.join(root,'release');const spool=path.join(root,'snapshot-1.ready');fs.mkdirSync(path.join(release,'apps/drupal-exporter'),{recursive:true});fs.mkdirSync(path.join(release,'config/drupal'),{recursive:true});fs.mkdirSync(path.join(release,'config/catalog-anomalies'),{recursive:true});fs.mkdirSync(spool,{mode:0o700});const lock=Buffer.from('{}\n');fs.writeFileSync(path.join(release,'apps/drupal-exporter/package-lock.json'),lock);fs.writeFileSync(path.join(release,'config/drupal/legacy-sku-collisions.yaml'),'collisions: []\n');fs.writeFileSync(path.join(release,'config/catalog-anomalies/publication-policy.yaml'),'rules: []\n');const provenance={schema:'bp.release-provenance/1',repository:'Stanislavikus/babypark-integration',commit:'a'.repeat(40),tree:'b'.repeat(40),package_lock_sha256:hash(lock),created_at:'2026-09-28T00:00:00.000Z'};const releaseBytes=Buffer.from(JSON.stringify(provenance,null,2)+'\n');fs.writeFileSync(path.join(release,'RELEASE.json'),releaseBytes);const files={'preflight.json':{},'collision-report.json':{},'anomaly-report.json':{},'source-acceptance.json':{schema:'bp.drupal.source-acceptance/1'}};for(const [name,value]of Object.entries(files))fs.writeFileSync(path.join(spool,name),JSON.stringify(value,null,2)+'\n',{mode:0o600});const chunk=Buffer.from('{"rows":[]}');fs.writeFileSync(path.join(spool,'phase0-000001.json'),chunk,{mode:0o600});const manifest={schema:'bp.drupal-exporter.spool/3',version:3,provider:'drupal',source_epoch:'epoch',snapshot_watermark:'1790553600000000',producer_commit:provenance.commit,producer_release_provenance_sha256:hash(releaseBytes),source_acceptance_sha256:hash(fs.readFileSync(path.join(spool,'source-acceptance.json'))),collision_config_sha256:hash(fs.readFileSync(path.join(release,'config/drupal/legacy-sku-collisions.yaml'))),anomaly_publication_policy_sha256:hash(fs.readFileSync(path.join(release,'config/catalog-anomalies/publication-policy.yaml'))),anomaly_report_sha256:hash(fs.readFileSync(path.join(spool,'anomaly-report.json'))),blocker_count:0,phase_row_counts:{phase0:0,phase1:0},chunk_count:1,chunks:[{filename:'phase0-000001.json',phase:0,rows:0,bytes:chunk.length,sha256:hash(chunk)}],total_canonical_rows:0};fs.writeFileSync(path.join(spool,'manifest.json'),JSON.stringify(manifest,null,2)+'\n',{mode:0o600});return{root,release,spool,options:{releaseRoot:release},manifest};}

test('strict spool verification freezes manifest and sequential chunk authority',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const spool=verifySpool(f.spool,f.options);assert.equal(spool.spoolManifestSha256,hash(spool.manifestBytes));assert.equal(readVerifiedChunk(spool,spool.manifest.chunks[0]).toString(),'{"rows":[]}');fs.appendFileSync(path.join(f.spool,'phase0-000001.json'),'x');assert.throws(()=>verifySpool(f.spool,f.options),/no longer matches/)});
test('spool rejects release/config/evidence mismatch and unexpected or symlink entries',t=>{for(const mutation of [f=>{f.manifest.producer_commit='c'.repeat(40)},f=>fs.appendFileSync(path.join(f.release,'config/drupal/legacy-sku-collisions.yaml'),'x'),f=>fs.appendFileSync(path.join(f.spool,'source-acceptance.json'),'x'),f=>fs.writeFileSync(path.join(f.spool,'extra'),'x',{mode:0o600})]){const f=fixture();try{mutation(f);if(f.manifest.producer_commit.startsWith('c'))fs.writeFileSync(path.join(f.spool,'manifest.json'),JSON.stringify(f.manifest,null,2)+'\n',{mode:0o600});assert.throws(()=>verifySpool(f.spool,f.options))}finally{fs.rmSync(f.root,{recursive:true,force:true})}}const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));fs.unlinkSync(path.join(f.spool,'preflight.json'));fs.symlinkSync('/dev/null',path.join(f.spool,'preflight.json'));assert.throws(()=>verifySpool(f.spool,f.options))});
test('run state freezes exact header, order and trailer and writes durably private',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const spool=verifySpool(f.spool,f.options);const state=createRunState(spool,'kid',{randomUUID:()=> 'run',now:()=>new Date('2026-09-28T00:01:00.000Z')});const header=parseRunHeader(Buffer.from(state.run_header_base64,'base64'),{runId:'run'});assert.deepEqual(header.layers.map(x=>x.layer),['taxonomy','content','commercial','stock']);assert.equal(header.publication_authority.spool_manifest_sha256,spool.spoolManifestSha256);assert.equal(parseTrailerV2(Buffer.from(state.trailer_base64,'base64'),{seq:2}).run_digest,state.run_digest);const dir=path.join(f.root,'state');writeRunState(dir,state);assert.equal(fs.statSync(dir).mode&0o777,0o700);assert.equal(fs.statSync(path.join(dir,`${spool.spoolManifestSha256}.json`)).mode&0o777,0o600);assert.deepEqual(readRunState(dir,spool),state);assert.throws(()=>validateRunState({...state,run_id:'changed'},spool))});
test('atomic failpoints leave old or next complete JSON',t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const spool=verifySpool(f.spool,f.options);const dir=path.join(f.root,'state');const state=createRunState(spool,'kid',{randomUUID:()=> 'run',now:()=>new Date('2026-09-28T00:01:00.000Z')});writeRunState(dir,state);for(const point of ['before_fsync','after_file_fsync','after_rename','after_directory_fsync']){const next={...state,updated_at:'2026-09-28T00:02:00.000Z'};assert.throws(()=>writeRunState(dir,next,{failpoint:point}));assert.doesNotThrow(()=>readRunState(dir,spool))}});
test('exclusive lock refuses a second owner and stale break refuses live process',t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'d2b-lock-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const h='a'.repeat(64);const lock=acquireSenderLock(root,h);assert.equal(inspectSenderLock(root,h).alive,true);assert.throws(()=>acquireSenderLock(root,h),e=>e.code==='D2B_SENDER_LOCKED');assert.throws(()=>breakStaleSenderLock(root,h),e=>e.code==='D2B_LOCK_OWNER_ALIVE');lock.release();assert.doesNotThrow(()=>acquireSenderLock(root,h).release())});
test('transport origin permits HTTPS and loopback HTTP only',()=>{assert.equal(validateOrigin('https://catalog.example'),'https://catalog.example');assert.equal(validateOrigin('http://127.0.0.1:8080'),'http://127.0.0.1:8080');for(const url of ['http://example.com','https://u:p@example.com','https://example.com/path','https://example.com?q=1'])assert.throws(()=>validateOrigin(url))});
test('sender sends exact sequence once, persists ACK/state, and is terminal on resume',async t=>{const f=fixture();t.after(()=>fs.rmSync(f.root,{recursive:true,force:true}));const stateDir=path.join(f.root,'sender');const config={stateDir,kid:'kid',maxAttempts:2};const bootstrap={schema:'bp.catalog.state/1',state:'BOOTSTRAP',accepting_ingest:true,blockers:[],current_generation:null,source_epoch:null,published_identity_revision:null,accepted_run:null,layers:Object.fromEntries(['taxonomy','content','commercial','stock'].map(x=>[x,{accepted_watermark:null,need_full:false,need_reconcile:false}]))};let accepted=null;const sent=[];const client={async state(){return{status:200,body:accepted??bootstrap,retryAfter:null}},async full(runId,seq,final,body){sent.push({runId,seq,final,body:Buffer.from(body)});if(!final)return{status:200,body:{schema:'bp.catalog.ingest-response/1',status:'STAGED',ack:{staged:true,run_id:runId,layer:'full',seq,body_sha256:hash(body)}}};const run=readRunState(stateDir,verifySpool(f.spool,f.options));const ack={accepted:true,generation_id:'generation',layer:'full',run_id:runId,run_digest:run.run_digest,source_watermark:f.manifest.snapshot_watermark};accepted={...bootstrap,state:'CURRENT',current_generation:'generation',source_epoch:'epoch',published_identity_revision:1,accepted_run:{run_id:runId,run_digest:run.run_digest,final_seq:2,accepted_at:'2026-09-28T00:02:00.000Z'},layers:Object.fromEntries(['taxonomy','content','commercial','stock'].map(x=>[x,{accepted_watermark:f.manifest.snapshot_watermark,need_full:false,need_reconcile:false}]))};return{status:200,body:{schema:'bp.catalog.ingest-response/1',status:'ACKED',ack}}}};const args={spoolPath:f.spool,config,verification:f.options,client,now:()=>new Date('2026-09-28T00:01:00.000Z'),sleep:async()=>{}};const result=await sendSpool(args);assert.equal(result.status,'STATE_CONFIRMED');assert.deepEqual(sent.map(x=>[x.seq,x.final]),[[0,false],[1,false],[2,true]]);const state=readRunState(stateDir,verifySpool(f.spool,f.options));assert.equal(state.transport_state,'STATE_CONFIRMED');assert.equal(state.first_seq0_attempt_started_at,'2026-09-28T00:01:00.000Z');await sendSpool(args);assert.equal(sent.length,3)});
