import { FullMapperError } from './production-full-mapper.mjs';
const SQL={
 writeBrand:'INSERT INTO brands(brand_id,name,provenance_json) VALUES(@brand_id,@name,@provenance_json)',
 writeCategory:'INSERT INTO categories(category_id,parent_id,name_json,provenance_json) VALUES(@category_id,@parent_id,@name_json,@provenance_json)',
 writeStore:'INSERT INTO stores(store_id,name,active,metadata_json) VALUES(@store_id,@name,@active,@metadata_json)',
 writeAttributeDefinition:'INSERT INTO attribute_defs(attribute_id,code,type,label_json,provenance_json) VALUES(@attribute_id,@code,@type,@label_json,@provenance_json)',
 writeProduct:'INSERT INTO products(product_id,kind,product_type,brand_id,default_variant_id,provenance_json,updated_at) VALUES(@product_id,@kind,@product_type,@brand_id,@default_variant_id,@provenance_json,@updated_at)',
 writeProductText:'INSERT INTO product_text(product_id,language,title,short_description,description,url) VALUES(@product_id,@language,@title,@short_description,@description,@url)',
 writeVariant:'INSERT INTO variants(variant_id,product_id,sku,sku_key,gtin,is_default,options_json,updated_at) VALUES(@variant_id,@product_id,@sku,@sku_key,@gtin,@is_default,@options_json,@updated_at)',
 writeOffer:'INSERT INTO variant_offers(variant_id,current_minor,regular_minor,currency,on_sale,commercial_availability,tax_included,valid_from,valid_to,source_updated_at) VALUES(@variant_id,@current_minor,@regular_minor,@currency,@on_sale,@commercial_availability,@tax_included,@valid_from,@valid_to,@source_updated_at)',
 writeStoreStock:'INSERT INTO store_stock(variant_id,store_id,quantity,source_updated_at) VALUES(@variant_id,@store_id,@quantity,@source_updated_at)',
 writeProductCategory:'INSERT INTO product_categories(product_id,category_id,is_primary) VALUES(@product_id,@category_id,@is_primary)',
 writeAttributeValue:'INSERT INTO product_attributes(owner_type,owner_id,attribute_id,value_json) VALUES(@owner_type,@owner_id,@attribute_id,@value_json)',
 writeImage:'INSERT INTO images(image_id,product_id,variant_id,url,role,position,metadata_json) VALUES(@image_id,@product_id,@variant_id,@url,@role,@position,@metadata_json)',
 writeKitComponent:'INSERT INTO kit_components(kit_product_id,component_variant_id,quantity,discount_minor,mutable,metadata_json) VALUES(@kit_product_id,@component_variant_id,@quantity,@discount_minor,@mutable,@metadata_json)'};
const dimension=new Set(['writeBrand','writeCategory','writeStore','writeAttributeDefinition']);
export function createCanonicalWriter(db){const api=Object.create(null),stmts=Object.fromEntries(Object.entries(SQL).map(([k,v])=>[k,db.prepare(v)]));for(const name of Object.keys(SQL))api[name]=row=>{try{stmts[name].run(row);}catch(e){if(dimension.has(name)&&String(e.code).startsWith('SQLITE_CONSTRAINT')){const table={writeBrand:['brands','brand_id'],writeCategory:['categories','category_id'],writeStore:['stores','store_id'],writeAttributeDefinition:['attribute_defs','attribute_id']}[name];const old=db.prepare(`SELECT * FROM ${table[0]} WHERE ${table[1]}=?`).get(row[table[1]]);if(old&&Object.keys(row).every(k=>old[k]===row[k]))return false;throw new FullMapperError('FULL_DIMENSION_CONFLICT','Dimension conflicts with canonical data',{constraint:e.code});}throw new FullMapperError(String(e.code).includes('FOREIGNKEY')?'FULL_MAPPER_REFERENCE_MISSING':'FULL_MAPPER_IDENTITY_CONFLICT','Canonical write constraint failed',{constraint:e.code??'unknown'});}};api.readAttributeDefinition=id=>db.prepare('SELECT * FROM attribute_defs WHERE attribute_id=?').get(id);api.setDefaultVariant=(productId,variantId)=>db.prepare('UPDATE products SET default_variant_id=? WHERE product_id=?').run(variantId,productId);return Object.freeze(api);}
